# site settings
title: La Maroquine
subtitle: créations artisanales ardéchoises en cuir 
email: camille.boirayon@gmail.com
phone: 06 88 34 03 88
description: Une panoplie de créations en cuir entièrement faites à la main.
logo: 'assets/images/logo.png'

baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Grégoire Colson

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
facebook_url: https://www.facebook.com/la.maroquine/
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://www.instagram.com/la.maroquine/

# build settings
markdown: kramdown

sass:
  style: compressed
